name: IPTV Checker & Updater

on:
  schedule:
    - cron: "0 22 * * 0"  # Runs every week, Monday 3:00 AM UTC+5 hours
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Combined Playlist from M3U Playlist URLs
        run: |
          # Define your M3U playlist URLs (one per line)
          cat <<EOF > playlist_links.txt
          https://iptv-org.github.io/iptv/index.category.m3u
          EOF

          while read -r url; do
            echo "Fetching $url"
            # Download the playlist; remove any duplicate "#EXTM3U" header lines
            curl -fsSL "$url" | sed '/^#EXTM3U/d' >> playlist.m3u
          done < playlist_links.txt

          echo "Combined playlist:"
          cat playlist.m3u
          
      - name: Ensure Playlist Header
        run: |
          if ! grep -q "^#EXTM3U" playlist.m3u; then
            sed -i '1i#EXTM3U' playlist.m3u
          fi
          echo "Ensured #EXTM3U header:"
          cat playlist.m3u    

      - name: Validate Playlist Format
        run: |
          if ! grep -q "^#EXTINF" playlist.m3u; then
            echo "Invalid playlist format: Missing #EXTINF lines"
            exit 1
          fi
          if ! grep -q "^http" playlist.m3u; then
            echo "Invalid playlist format: Missing HTTP links"
            exit 1
          fi
    
      - name: Install Dependencies and iptv-checker via npm
        run: |
          sudo apt update
          sudo apt install -y nodejs npm curl jq ffmpeg
          npm install -g iptv-checker
          export PATH=$PATH:$(npm bin -g)
          
      - name: Create Output Directory
        run: mkdir -p output

      - name: Run iptv-checker on the Playlist
        run: |
          set -e
          if ! iptv-checker playlist.m3u -o output; then
            echo "Unable to parse the playlist"
            exit 1
          fi
          echo "#EXTM3U" > output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Saudi Quran" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/saudiquransd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Saudi Sunnah" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/saudisunnahsd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Ary QTV" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/aryqtvsd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Madni TV" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/madnitvsd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Animal Planet" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/skyanimalplanetddr/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", National Geographic" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/skynatgeo/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Action Movies" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/osnmovieaction/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Sky Cinema" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/skycinemapremier/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", OSN movies" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/osnmovies/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", OSN Series" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/osnseries/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Sky Cinema Sci-fi" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/skycinemascifi/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", 8xm" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/8xmsd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Jalwa Music" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/jalwamusicsd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", A Plus" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/aplushd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Aan TV" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/aantvhd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", A TV" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/atvhd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Aur Life" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/aurlifehdddr/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Aaj TV" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/aajtvsd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Apna TV" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/apnatv/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Ary Digital" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/arydigitalhd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Geo TV" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/geotvhdddr/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Hum TV" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/humtvsdddr/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", 24 News" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/24newshd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", 7 News" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/7newshd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", 92 News" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/92newshdddr/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Abn News" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/abnnewshd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Aaj News" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/aajnewssd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Abbtak News" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/abbtaknewssd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Ary News" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/arynewssd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Bol News" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/bolnewshd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Channel Five" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/channelfive/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Dawn News" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/dawnnewssd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Dunya News" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/dunyanewshd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Express News" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/expressnewssd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Geo News" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/geonewshdddr/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Hum News" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/humnewshd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Ktn News" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/ktnnewshd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Khyber News" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/khybernewssd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Lahore news" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/lahorenewshd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Neo News" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/neonewshd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Pnn News" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/pnnnewshd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Sindh News" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/sindhnewssd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Talon News" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/talonnewshd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Vsh News" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/vshnewssd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Ptv News" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/ptvnewshd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Play TV" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/playtvsd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Public News" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/publicnewshd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Such News" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/suchnewshd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Samaa News" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/samaanewssdddr/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Suno News" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/sunonewshd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", A Sports" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/asportssd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Astro Cric" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/astrocrichd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Ptv Sports" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/ptvsportssd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Super Sports EPL" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/supersportseplhd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Starz Play Cric" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/starzplaycric/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Sky Sports Cric" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/skysportscrichd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Sky Sports EPL" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/skysportseplhd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Sky Main Event" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/skyspmainevent/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Willow Cricket Xtra" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/willowcricketxtra/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Ten Sports" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/tensportssdddr/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Willow Cric" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/willowcrichd/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          echo "##EXTINF:-1, group-title="Pakistan", Sky Sports WWE" >> output/final_playlist.m3u
          echo "http://webtv.dodear.asia:88/skysportswwe/tracks-v1a1/mono.m3u8" >> output/final_playlist.m3u
          cat output/online.m3u >> output/final_playlist.m3u
          echo "Final Playlist:"
          cat output/final_playlist.m3u

      - name: Commit & Push Updated Working Playlist to Repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          git add output/final_playlist.m3u
          git commit -m "Update working IPTV playlist $(date)" || echo "No changes to commit"
          git push "https://${GITHUB_TOKEN}@github.com/${{ github.repository }}.git"

      - name: Update Gist with Working Playlist (Optional)
        env:
          GIST_ID: ${{ secrets.GIST_ID }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        run: |
          if [ -z "${GIST_ID}" ] || [ -z "${GIST_TOKEN}" ]; then
            echo "Skipping Gist update: GIST_ID or GIST_TOKEN is not set."
          else
            echo "Updating Gist..."
            payload=$(jq -n --arg content "$(cat output/final_playlist.m3u)" '{"files": {"final_playlist.m3u": {"content": $content}}}')
            echo "$payload" > payload.json
            curl -X PATCH "https://api.github.com/gists/${GIST_ID}" \
              -H "Authorization: token ${GIST_TOKEN}" \
              -H "Content-Type: application/json" \
              -d @payload.json
          fi
